CREATE TABLE orders_pay (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', order_id INT DEFAULT NULL, collection_id VARCHAR(255) DEFAULT NULL, collection_status VARCHAR(255) DEFAULT NULL, external_reference VARCHAR(255) DEFAULT NULL, merchant_account_id VARCHAR(255) DEFAULT NULL, merchant_order_id VARCHAR(255) DEFAULT NULL, payment_id VARCHAR(255) DEFAULT NULL, payment_type VARCHAR(255) DEFAULT NULL, preference_id VARCHAR(255) DEFAULT NULL, processing_mode VARCHAR(255) DEFAULT NULL, site_id VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_delete TINYINT(1) NOT NULL, INDEX IDX_FA24C3D48D9F6D38 (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
     ALTER TABLE orders_pay ADD CONSTRAINT FK_FA24C3D48D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id);
     ALTER TABLE productor ADD company_id CHAR(36) DEFAULT NULL COMMENT '(DC2Type:guid)', ADD is_super TINYINT(1) NOT NULL;
     ALTER TABLE productor ADD CONSTRAINT FK_173A070979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id);
     CREATE INDEX IDX_173A070979B1AD6 ON productor (company_id);

CREATE TABLE page (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', name VARCHAR(255) NOT NULL, content VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_delete TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE page CHANGE content content LONGTEXT NOT NULL;

ALTER TABLE sinister_item DROP FOREIGN KEY FK_68AD9F3F3E67426B;
     ALTER TABLE sinister_item ADD CONSTRAINT FK_68AD9F3F3E67426B FOREIGN KEY (sinister_id) REFERENCES sinister (id) ON DELETE SET NULL;