SET foreign_key_checks = 0;
truncate table cart;
truncate table cart_item;
truncate table category;
truncate table company;
truncate table customer;
truncate table demo;
truncate table log;
truncate table orders;
truncate table orders_item;
truncate table product;
truncate table provider;
truncate table product_category;
truncate table productor;
truncate table product_picture;
truncate table sinister;
truncate table slider;
truncate table transporter;
truncate table upload;
SET foreign_key_checks = 1;