inamika_api:
    resource: "@InamikaApiBundle/Resources/config/routing.yml"
    prefix:   /api
    defaults:
        _format: json

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
