<?php

namespace Inamika\BackEndBundle\Repository;

/**
 * SinisterItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinisterItemRepository extends \Doctrine\ORM\EntityRepository
{
    
}
