api_carts_post:
    path:     /carts
    defaults: { _controller: InamikaApiBundle:Carts:post }
    methods: [POST]
api_carts_get:
    path:     /carts/{customer}
    defaults: { _controller: InamikaApiBundle:Carts:GET }
    methods: [GET]
api_carts_get_preference:
    path:     /carts/api_carts_get_preference/{id}
    defaults: { _controller: InamikaApiBundle:Carts:getPreference }
    methods: [GET]
