api_productors:
    path:     /productors
    defaults: { _controller: InamikaApiBundle:Productors:index }
    methods: [GET]

api_productors_get:
    path:     /productors/{id}
    defaults: { _controller: InamikaApiBundle:Productors:get }
    methods: [GET]

api_productors_get_byCompany:
    path:     /productorsByCompany/{companyId}
    defaults: { _controller: InamikaApiBundle:Productors:getByCompany }
    methods: [GET]

api_productors_post:
    path:     /productors
    defaults: { _controller: InamikaApiBundle:Productors:post }
    methods: [POST]

api_productors_login:
    path:     /productors/login
    defaults: { _controller: InamikaApiBundle:Productors:login }
    methods: [POST]

api_productors_put:
    path:     /productors/{id}
    defaults: { _controller: InamikaApiBundle:Productors:put }
    methods: [PUT]

api_productors_delete:
    path:     /productors/{id}
    defaults: { _controller: InamikaApiBundle:Productors:delete }
    methods: [DELETE]
