api_sinisters:
    path:     /sinisters
    defaults: { _controller: InamikaApiBundle:Sinisters:index }
    methods: [GET]

api_sinisters_ByProductor:
    path:     /sinisters/ByProductor/{productor}
    defaults: { _controller: InamikaApiBundle:Sinisters:byProductor }
    methods: [GET]

api_sinisters_get:
    path:     /sinisters/{id}
    defaults: { _controller: InamikaApiBundle:Sinisters:get }
    methods: [GET]

api_sinisters_changeSatus:
    path:     /sinisters/changeSatus/{id}
    defaults: { _controller: InamikaApiBundle:Sinisters:changeSatus }
    methods: [PUT]

api_sinisters_today:
    path:     /sinistersToday
    defaults: { _controller: InamikaApiBundle:Sinisters:today }
    methods: [GET]

api_sinisters_post:
    path:     /sinisters
    defaults: { _controller: InamikaApiBundle:Sinisters:post }
    methods: [POST]

api_sinisters_put:
    path:     /sinisters/{id}
    defaults: { _controller: InamikaApiBundle:Sinisters:put }
    methods: [PUT]

api_sinisters_delete:
    path:     /sinisters/{id}
    defaults: { _controller: InamikaApiBundle:Sinisters:delete }
    methods: [DELETE]
